pipelines:
  - name: test_deployment
    steps:
      - name: deploy_webapp
        type: deployment/Webapp
        configuration:
          dryRun: true
          container: 
            repo: ${runVarImageName}
            tag: ${runVarImageTag}
          # webApp: 
          #   path: myrepo/awesome-app.3.0.0.jar
          #   technology: wildfly
          # ansible:
          #   role: wildfly
          #   inventory: uat
          inputResources:
            # - name: my_cron
            - name: vm_group1
            - name: wh_jenkins1
          integrations:
            - name: artifactory_eu
        execution:
          onStart:
            - echo $(echo "$res_wh_jenkins1_payload" | jq '.image_name')
            - add_run_variables runVarImageName=`echo "$res_wh_jenkins1_payload" | jq -r '.image_name'`
            - add_run_variables runVarImageTag=`echo "$res_wh_jenkins1_payload" | jq -r '.image_tag'`

