pipeline {
    agent any


    stages {

        stage ('Cleanup')
        {
            steps {
                cleanWs()
            }
        }

        stage ('Clone') {
            steps {
                git branch: 'main', url: "https://github.com/jfrog/SwampUp2021.git"
            }
        }


        stage ('Artifactory configuration') {
            steps {
                dir('SU-113-Jfrog-Artifactory-Essentials/npm-example'){
                    rtServer ( id: "swampup113",url: SERVER_URL,credentialsId: "CREDENTIALS_SWAMPUP")
                    rtNpmResolver (id: "NPM_RESOLVER",serverId: "swampup113",repo: "swampup-npm-remote")
                    rtNpmDeployer (id: "NPM_DEPLOYER",serverId: "swampup113",repo: "swampup-npm-dev-local")
                }
            }
        }

        stage ('Exec npm install and publish') {
            steps {
                dir('SU-113-Jfrog-Artifactory-Essentials/npm-example'){
                    rtNpmInstall (tool: "NPM_TOOL", resolverId: "NPM_RESOLVER")
                    rtNpmPublish (tool: "NPM_TOOL", deployerId: "NPM_DEPLOYER")
                }
            }
        }

        stage ('Publish build info') {
            steps {
                rtPublishBuildInfo (serverId: "swampup113")
            }
        }
    }
}